const fs = require('fs');

const dadJokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "What's the best part about living in Switzerland? I don't know, but the flag is a big plus.",
    "I've got a pen that can write underwater. It can write other words too but underwater is one of my faves.",
    "I went for an interview. They said 'Can you perform under pressure?' I said 'I’m not sure about that but I can have a good crack at Bohemian Rhapsody'",
    "How much do roofs cost? \n Nothing. They’re on the house.",
    "The other day I bought a thesaurus, but when I got home and opened it, all the pages were blank... I can’t find the words to describe how angry I am.",
    "Just adopted a dog from the local blacksmith, soon as I got him home he made a bolt for the door.",
    "The Police just arrested the world's tongue twister champion. They say he'll be given a tough sentence.",
    "I had a neck brace fitted a few years ago......since then I’ve never looked back.",
    "The only thing flat-earthers fear is sphere itself.",
    "What did the bra say to the hat? 'You go on ahead, I'll give these two a lift!'",
    "Did you hear about the cheese factory that got blown up? Da brie was everywhere.",
    "Why can’t Elsa be trusted to hold a balloon? Because she’ll 'Let it Go'!",
    "You know, I always wondered why stage actors were told to 'break a leg'. Then I remembered its because they are part of a cast...",
    "I used to be addicted to the Hokey Cokey, but I managed to turn myself around.",
    "What do you call it when James Bond takes a bath? Bubble 07.",
    "Did you hear the rumor about butter? Well, I'm not going to go spreading it.",
    "Why is Peter Pan always flying? Because he Neverlands.",
    "Where are all the dad jokes stored? In a dad-a-base.",
    "Why couldn't the bicycle stand up by itself? It was two tired.",
    "I hated facial hair but then it grew on me.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Did you hear about the claustrophobic astronaut? He just wanted a bit more space.",
    "I was just reminiscing about the beautiful herb garden I had when I was growing up. Good thymes.",
    "What kind of underpants does a cloud wear... Thunder pants!",
    "I hate my job—all I do is crush cans all day. It’s soda pressing.",
    "What did the policeman say to his bellybutton? You’re under a vest.",
    "I was thinking of having a tattoo of rabbits on my head because from a distance they look like hares.",
    "Why did the orange lose the race? It ran out of juice.",
    "What do you call a teacher whose always late? Mister Bus.",
    "Why did the man fall down the well? Because he couldn’t see that well.",
    "What kind of ghost has the best hearing? The eeriest.",
    "What's the best time to visit a dentist? Two thirty.",
    "Did you know that seven days running makes one week, the listener replies yes, Monday to Sunday, I said I meant seven days running makes one weak!",
    "Why do birds hate the internet? They do not know how to tweet.",
    "My sister was pregnant with her 5th baby and she was saying how she wasn’t having anymore she was struggling to pick a name so my dad said 'why don’t you call it Thursday' she said 'that’s unusual what made you think of that' he said 'when people ask you how many kids you have say 4 but when I’ve had this one I’m going to call it a day'. True story!!!",
    "Did you hear about the cowboy with paper trousers? He got arrested for rustling!!",
    "How do astronomers organize a party? They planet.",
    "Dad walks into a bar... he got disqualified from the limbo competition.",
    "My dad said to me 'Why do you never succeed?'. I said 'because I am not a budgie!'.",
    "I only seem to get sick on weekdays. I must have a weekend immune system.",
    "How do cows stay up to date? They read the Moo-spaper.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere!",
    "Why do people say 'break a leg' when you go on stage? Because every play has a cast.",
    "I bought a greyhound a month ago. A friend of mine said, 'What are you going to do with it?' I said, 'I'm gonna race it.' He said, 'By the look of it, I think you'll beat it.'",
    "What’s the difference between Dad and a hat? A hat only blows off on windy days...",
    "How do you approach an angry Welshman? Caerphilly.",
    "Me: I’m hungry Dad: I’m James, nice to meet you!",
    "I walked into a bar the other day... screamed aaarrhhh... it was an iron bar.",
    "What’s the difference between a dirty bus stop and a lobster with boob implants? Ones a crusty bus station, the others a busty crustacean.",
    "My dog's got no nose! How does he smell? Awful…",
    "Which days are the strongest? Saturday and Sunday. The rest are weekdays.",
    "Why can't a leopard hide? He's always spotted.",
    "What did the octogenarian pirate say? Aye matey!",
    "Two ladies looking at dresses in a clothes shop window, one says to the other 'that’s the one I’d get' and a Cyclopes came out and ate them both!",
    "I'm afraid for the calendar. Its days are numbered.",
    "My wife said I should do lunges to stay in shape. That would be a big step forward.",
    "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
    "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
    "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "How do you follow Will Smith in the snow? You follow the fresh prints.",
    "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
    "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
    "How does dry skin affect you at work? You don’t have any elbow grease to put into it.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "Dear Math, grow up and solve your own problems.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Have you heard about the chocolate record player? It sounds pretty sweet.",
    "Wanna hear a joke about paper? Never mind—it's tearable.",
    "What's the best way to watch a fly fishing tournament? Live stream.",
    "Spring is here! I got so excited I wet my plants.",
    "I could tell a joke about pizza, but it's a little cheesy.",
    "Don't trust atoms. They make up everything!",
    "When does a joke become a dad joke? When it becomes apparent.",
    "I wouldn't buy anything with velcro. It's a total rip-off.",
    "What’s an astronaut’s favorite part of a computer? The space bar.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
    "Why are elevator jokes so classic and good? They work on many levels.",
    "Why do bees have sticky hair? Because they use a honeycomb.",
    "Which state has the most streets? Rhode Island.",
    "What did the coffee report to the police? A mugging.",
    "What did the fish say when he hit the wall? Dam.",
    "Is this pool safe for diving? It deep ends.",
    "If you see a crime happen at the Apple store, what does it make you? An iWitness."
];

module.exports = {
  name: 'dadjokes',
  description: 'Get a random dad joke!',
  
  callback: (client, interaction) => {
    const randomJoke = dadJokes[Math.floor(Math.random() * dadJokes.length)];
    interaction.reply(randomJoke);
  },
};
